services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: greeny
      MYSQL_USER: greeny
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234